version: "3.8"
services:
  web:
    environment:
      - BLAZEGRAPH_SERVICE=blazegraph
      - BLAZEGRAPH_PORT=8080
      - ENVIRONMENT=DOCKER-COMPOSE
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "3001:3000"
    links:
      - blazegraph
  blazegraph:
    build:
      context: .
      dockerfile: Dockerfile_blazegraph
    ports:
      - "8890:8080"
